FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt requirements-test.txt ./
RUN pip install --no-cache-dir -r requirements-test.txt
COPY . .
ENV PYTHONPATH=/app
CMD ["pytest", "app/tests/", "-v", "--cov=app", "--cov-report=term", "--cov-report=html", "--asyncio-mode=auto"]